version: "3.8"
  
services:
  redis:
    image: redis:buster
  web:
    build:
      context: ./web/
    ports:
      - "8000:8000"
    links:
      - redis
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web