version: '3.8'
services:
  trainingdb_service:
    image: octokami/trainingdbapi:0.0.1
    environment:
      - DB_URL=sqlite:///features.db
    networks:
      - training-pipeline
    ports:
      - "5000:5000"
  training_service:
    image: octokami/trainapi-gcs:0.0.1
    depends_on:
      - trainingdb_service
    environment:
      - TRAININGDB_API=http://trainingdb_service:5000/training-db/diabetes
      - MODEL_REPO=model_repo_de2021
      - PROJECT_ID=yourprojectidhere
    networks:
      - training-pipeline
    ports:
      - "5001:5000"
  prediction_service:
    image: octokami/predictionapi-gcs:0.0.1
    depends_on:
      - training_service
    environment:
      - MODEL_REPO=model_repo_de2021
      - PROJECT_ID=yourprojectidhere
    networks:
      - prediction-pipeline
    ports:
      - "5002:5000"
networks:
  training-pipeline:
    driver: overlay
  prediction-pipeline:
    driver: overlay
